export const snippetsData = [
  {
    id: 1,
    name: 'Welcome Component',
    category: 'react',
    language: 'JSX',
    description: 'A simple functional component that displays a greeting',
    tags: ['component', 'functional', 'beginner'],
    difficulty: 'beginner',
    views: 1234,
    rating: 4.8,
    lines: [
      { num: 1, text: "import React from 'react';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "function Welcome({ name }) {", color: "#93c5fd" },
      { num: 4, text: "  return (", color: "#ffffff" },
      { num: 5, text: "    <h1 className=\"text-2xl\">", color: "#6ee7b7" },
      { num: 6, text: "      Hello, {name}", color: "#ffffff" },
      { num: 7, text: "    </h1>", color: "#6ee7b7" },
      { num: 8, text: "  );", color: "#ffffff" },
      { num: 9, text: "}", color: "#93c5fd" },
      { num: 10, text: "", color: "" },
      { num: 11, text: "export default Welcome;", color: "#a78bfa" },
    ]
  },
  {
    id: 2,
    name: 'Custom Hook - useLocalStorage',
    category: 'react',
    language: 'JavaScript',
    description: 'A reusable hook for persisting state to localStorage',
    tags: ['hook', 'storage', 'intermediate'],
    difficulty: 'intermediate',
    views: 3456,
    rating: 4.9,
    lines: [
      { num: 1, text: "function useLocalStorage(key, initialValue) {", color: "#93c5fd" },
      { num: 2, text: "  const [storedValue, setStoredValue] = useState(() => {", color: "#ffffff" },
      { num: 3, text: "    try {", color: "#fbbf24" },
      { num: 4, text: "      const item = window.localStorage.getItem(key);", color: "#ffffff" },
      { num: 5, text: "      return item ? JSON.parse(item) : initialValue;", color: "#6ee7b7" },
      { num: 6, text: "    } catch (error) {", color: "#fbbf24" },
      { num: 7, text: "      console.log(error);", color: "#f87171" },
      { num: 8, text: "      return initialValue;", color: "#6ee7b7" },
      { num: 9, text: "    }", color: "#fbbf24" },
      { num: 10, text: "  });", color: "#ffffff" },
      { num: 11, text: "", color: "" },
      { num: 12, text: "  const setValue = (value) => {", color: "#93c5fd" },
      { num: 13, text: "    setStoredValue(value);", color: "#ffffff" },
      { num: 14, text: "    window.localStorage.setItem(key, JSON.stringify(value));", color: "#ffffff" },
      { num: 15, text: "  };", color: "#ffffff" },
      { num: 16, text: "", color: "" },
      { num: 17, text: "  return [storedValue, setValue];", color: "#6ee7b7" },
      { num: 18, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 3,
    name: 'Debounce Function',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Utility function to debounce rapid function calls',
    tags: ['utility', 'performance', 'intermediate'],
    difficulty: 'intermediate',
    views: 2890,
    rating: 4.7,
    lines: [
      { num: 1, text: "function debounce(func, delay) {", color: "#93c5fd" },
      { num: 2, text: "  let timeoutId;", color: "#ffffff" },
      { num: 3, text: "", color: "" },
      { num: 4, text: "  return function (...args) {", color: "#93c5fd" },
      { num: 5, text: "    clearTimeout(timeoutId);", color: "#ffffff" },
      { num: 6, text: "", color: "" },
      { num: 7, text: "    timeoutId = setTimeout(() => {", color: "#fbbf24" },
      { num: 8, text: "      func.apply(this, args);", color: "#ffffff" },
      { num: 9, text: "    }, delay);", color: "#fbbf24" },
      { num: 10, text: "  };", color: "#ffffff" },
      { num: 11, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 4,
    name: 'Props Validation Component',
    category: 'react',
    language: 'JSX',
    description: 'Component with prop types validation',
    tags: ['component', 'validation', 'beginner'],
    difficulty: 'beginner',
    views: 2145,
    rating: 4.6,
    lines: [
      { num: 1, text: "import PropTypes from 'prop-types';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "function UserCard({ user, onDelete }) {", color: "#93c5fd" },
      { num: 4, text: "  return (", color: "#ffffff" },
      { num: 5, text: "    <div className=\"card\">", color: "#6ee7b7" },
      { num: 6, text: "      <h2>{user.name}</h2>", color: "#ffffff" },
      { num: 7, text: "      <p>{user.email}</p>", color: "#ffffff" },
      { num: 8, text: "      <button onClick={onDelete}>Delete</button>", color: "#ffffff" },
      { num: 9, text: "    </div>", color: "#6ee7b7" },
      { num: 10, text: "  );", color: "#ffffff" },
      { num: 11, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 5,
    name: 'Fetch API with Error Handling',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Robust API call pattern with error handling',
    tags: ['api', 'async', 'intermediate'],
    difficulty: 'intermediate',
    views: 4567,
    rating: 4.9,
    lines: [
      { num: 1, text: "async function fetchData(url) {", color: "#93c5fd" },
      { num: 2, text: "  try {", color: "#fbbf24" },
      { num: 3, text: "    const response = await fetch(url);", color: "#ffffff" },
      { num: 4, text: "", color: "" },
      { num: 5, text: "    if (!response.ok) {", color: "#6ee7b7" },
      { num: 6, text: "      throw new Error(`HTTP Error: ${response.status}`);", color: "#f87171" },
      { num: 7, text: "    }", color: "#6ee7b7" },
      { num: 8, text: "", color: "" },
      { num: 9, text: "    const data = await response.json();", color: "#ffffff" },
      { num: 10, text: "    return data;", color: "#6ee7b7" },
      { num: 11, text: "  } catch (error) {", color: "#fbbf24" },
      { num: 12, text: "    console.error('Fetch error:', error);", color: "#f87171" },
      { num: 13, text: "    throw error;", color: "#f87171" },
      { num: 14, text: "  }", color: "#fbbf24" },
      { num: 15, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 6,
    name: 'Memoized Component',
    category: 'react',
    language: 'JSX',
    description: 'Performance optimized component using React.memo',
    tags: ['performance', 'optimization', 'advanced'],
    difficulty: 'advanced',
    views: 2876,
    rating: 4.8,
    lines: [
      { num: 1, text: "import React, { memo } from 'react';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "const UserList = memo(({ users, onSelect }) => {", color: "#93c5fd" },
      { num: 4, text: "  return (", color: "#ffffff" },
      { num: 5, text: "    <ul className=\"user-list\">", color: "#6ee7b7" },
      { num: 6, text: "      {users.map(user => (", color: "#ffffff" },
      { num: 7, text: "        <li key={user.id} onClick={() => onSelect(user)}>", color: "#ffffff" },
      { num: 8, text: "          {user.name}", color: "#ffffff" },
      { num: 9, text: "        </li>", color: "#ffffff" },
      { num: 10, text: "      ))}", color: "#ffffff" },
      { num: 11, text: "    </ul>", color: "#6ee7b7" },
      { num: 12, text: "  );", color: "#ffffff" },
      { num: 13, text: "});", color: "#93c5fd" },
    ]
  },
  {
    id: 7,
    name: 'Array Filter & Map',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Chained array operations for data transformation',
    tags: ['array', 'functional', 'beginner'],
    difficulty: 'beginner',
    views: 3210,
    rating: 4.7,
    lines: [
      { num: 1, text: "const users = [", color: "#ffffff" },
      { num: 2, text: "  { id: 1, name: 'Alice', active: true },", color: "#ffffff" },
      { num: 3, text: "  { id: 2, name: 'Bob', active: false },", color: "#ffffff" },
      { num: 4, text: "  { id: 3, name: 'Charlie', active: true },", color: "#ffffff" },
      { num: 5, text: "];", color: "#ffffff" },
      { num: 6, text: "", color: "" },
      { num: 7, text: "const activeNames = users", color: "#93c5fd" },
      { num: 8, text: "  .filter(user => user.active)", color: "#6ee7b7" },
      { num: 9, text: "  .map(user => user.name);", color: "#6ee7b7" },
      { num: 10, text: "", color: "" },
      { num: 11, text: "console.log(activeNames);", color: "#fbbf24" },
      { num: 12, text: "// ['Alice', 'Charlie']", color: "#64748b" },
    ]
  },
  {
    id: 8,
    name: 'useEffect Hook Pattern',
    category: 'react',
    language: 'JSX',
    description: 'Common patterns for useEffect with cleanup functions',
    tags: ['hook', 'lifecycle', 'intermediate'],
    difficulty: 'intermediate',
    views: 3567,
    rating: 4.8,
    lines: [
      { num: 1, text: "import { useState, useEffect } from 'react';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "export function DataFetcher({ id }) {", color: "#93c5fd" },
      { num: 4, text: "  const [data, setData] = useState(null);", color: "#ffffff" },
      { num: 5, text: "", color: "" },
      { num: 6, text: "  useEffect(() => {", color: "#fbbf24" },
      { num: 7, text: "    const controller = new AbortController();", color: "#ffffff" },
      { num: 8, text: "    fetch(`/api/data/${id}`, { signal: controller.signal })", color: "#ffffff" },
      { num: 9, text: "      .then(r => r.json())", color: "#ffffff" },
      { num: 10, text: "      .then(setData);", color: "#ffffff" },
      { num: 11, text: "    return () => controller.abort();", color: "#6ee7b7" },
      { num: 12, text: "  }, [id]);", color: "#fbbf24" },
      { num: 13, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 9,
    name: 'Throttle Function',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Rate-limiting function for expensive operations',
    tags: ['utility', 'performance', 'intermediate'],
    difficulty: 'intermediate',
    views: 2543,
    rating: 4.7,
    lines: [
      { num: 1, text: "function throttle(func, limit) {", color: "#93c5fd" },
      { num: 2, text: "  let inThrottle;", color: "#ffffff" },
      { num: 3, text: "  return function (...args) {", color: "#93c5fd" },
      { num: 4, text: "    if (!inThrottle) {", color: "#6ee7b7" },
      { num: 5, text: "      func.apply(this, args);", color: "#ffffff" },
      { num: 6, text: "      inThrottle = true;", color: "#ffffff" },
      { num: 7, text: "      setTimeout(() => inThrottle = false, limit);", color: "#ffffff" },
      { num: 8, text: "    }", color: "#6ee7b7" },
      { num: 9, text: "  };", color: "#ffffff" },
      { num: 10, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 10,
    name: 'REST API Handler',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Complete REST API handler with CRUD operations',
    tags: ['api', 'rest', 'advanced'],
    difficulty: 'advanced',
    views: 2134,
    rating: 4.9,
    lines: [
      { num: 1, text: "class APIClient {", color: "#93c5fd" },
      { num: 2, text: "  constructor(baseURL) { this.baseURL = baseURL; }", color: "#ffffff" },
      { num: 3, text: "", color: "" },
      { num: 4, text: "  async get(endpoint) {", color: "#fbbf24" },
      { num: 5, text: "    return fetch(`${this.baseURL}${endpoint}`)", color: "#ffffff" },
      { num: 6, text: "      .then(r => r.json());", color: "#ffffff" },
      { num: 7, text: "  }", color: "#fbbf24" },
      { num: 8, text: "", color: "" },
      { num: 9, text: "  async post(endpoint, data) {", color: "#fbbf24" },
      { num: 10, text: "    return fetch(`${this.baseURL}${endpoint}`, {", color: "#ffffff" },
      { num: 11, text: "      method: 'POST',", color: "#ffffff" },
      { num: 12, text: "      headers: { 'Content-Type': 'application/json' },", color: "#ffffff" },
      { num: 13, text: "      body: JSON.stringify(data)", color: "#ffffff" },
      { num: 14, text: "    }).then(r => r.json());", color: "#ffffff" },
      { num: 15, text: "  }", color: "#fbbf24" },
      { num: 16, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 11,
    name: 'Redux Slice Pattern',
    category: 'react',
    language: 'JavaScript',
    description: 'Modern Redux state management with Redux Toolkit',
    tags: ['state-management', 'redux', 'advanced'],
    difficulty: 'advanced',
    views: 1987,
    rating: 4.8,
    lines: [
      { num: 1, text: "import { createSlice } from '@reduxjs/toolkit';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "const counterSlice = createSlice({", color: "#93c5fd" },
      { num: 4, text: "  name: 'counter',", color: "#ffffff" },
      { num: 5, text: "  initialState: { value: 0 },", color: "#ffffff" },
      { num: 6, text: "  reducers: {", color: "#ffffff" },
      { num: 7, text: "    increment: (state) => { state.value += 1; },", color: "#6ee7b7" },
      { num: 8, text: "    decrement: (state) => { state.value -= 1; },", color: "#6ee7b7" },
      { num: 9, text: "  }", color: "#ffffff" },
      { num: 10, text: "});", color: "#93c5fd" },
    ]
  },
  {
    id: 12,
    name: 'Recursive Tree Traversal',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Recursively traverse and transform tree data structures',
    tags: ['recursion', 'data-structures', 'advanced'],
    difficulty: 'advanced',
    views: 1654,
    rating: 4.7,
    lines: [
      { num: 1, text: "function flattenTree(node, result = []) {", color: "#93c5fd" },
      { num: 2, text: "  if (!node) return result;", color: "#ffffff" },
      { num: 3, text: "", color: "" },
      { num: 4, text: "  result.push(node.value);", color: "#ffffff" },
      { num: 5, text: "", color: "" },
      { num: 6, text: "  if (node.children) {", color: "#6ee7b7" },
      { num: 7, text: "    node.children.forEach(child =>", color: "#ffffff" },
      { num: 8, text: "      flattenTree(child, result)", color: "#ffffff" },
      { num: 9, text: "    );", color: "#ffffff" },
      { num: 10, text: "  }", color: "#6ee7b7" },
      { num: 11, text: "", color: "" },
      { num: 12, text: "  return result;", color: "#6ee7b7" },
      { num: 13, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 13,
    name: 'Promise.all Parallel Requests',
    category: 'javascript',
    language: 'JavaScript',
    description: 'Execute multiple async operations in parallel',
    tags: ['async', 'promise', 'intermediate'],
    difficulty: 'intermediate',
    views: 2876,
    rating: 4.8,
    lines: [
      { num: 1, text: "async function fetchMultiple(urls) {", color: "#93c5fd" },
      { num: 2, text: "  try {", color: "#fbbf24" },
      { num: 3, text: "    const responses = await Promise.all(", color: "#ffffff" },
      { num: 4, text: "      urls.map(url => fetch(url))", color: "#ffffff" },
      { num: 5, text: "    );", color: "#ffffff" },
      { num: 6, text: "", color: "" },
      { num: 7, text: "    const data = await Promise.all(", color: "#ffffff" },
      { num: 8, text: "      responses.map(r => r.json())", color: "#ffffff" },
      { num: 9, text: "    );", color: "#ffffff" },
      { num: 10, text: "", color: "" },
      { num: 11, text: "    return data;", color: "#6ee7b7" },
      { num: 12, text: "  } catch (error) {", color: "#fbbf24" },
      { num: 13, text: "    console.error('Request failed:', error);", color: "#f87171" },
      { num: 14, text: "  }", color: "#fbbf24" },
      { num: 15, text: "}", color: "#93c5fd" },
    ]
  },
  {
    id: 14,
    name: 'Context API Setup',
    category: 'react',
    language: 'JSX',
    description: 'Global state management with React Context API',
    tags: ['context', 'state', 'intermediate'],
    difficulty: 'intermediate',
    views: 2345,
    rating: 4.8,
    lines: [
      { num: 1, text: "import React, { createContext, useContext } from 'react';", color: "#a78bfa" },
      { num: 2, text: "", color: "" },
      { num: 3, text: "const ThemeContext = createContext();", color: "#93c5fd" },
      { num: 4, text: "", color: "" },
      { num: 5, text: "export function ThemeProvider({ children }) {", color: "#93c5fd" },
      { num: 6, text: "  const [theme, setTheme] = useState('light');", color: "#ffffff" },
      { num: 7, text: "  return (", color: "#ffffff" },
      { num: 8, text: "    <ThemeContext.Provider value={{ theme, setTheme }}>", color: "#6ee7b7" },
      { num: 9, text: "      {children}", color: "#ffffff" },
      { num: 10, text: "    </ThemeContext.Provider>", color: "#6ee7b7" },
      { num: 11, text: "  );", color: "#ffffff" },
      { num: 12, text: "}", color: "#93c5fd" },
    ]
  },
];
